---
# tasks file for powershell
- include_tasks: "{{item}}"
  with_first_found:
    - "{{ansible_os_family}}-{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    - "{{ansible_pkg_mgr}}.yml"
    - "generic.yml"

